config/routes.rb
Rails.application.routes.draw do
  get 'common/index'

  devise_for :audit_users
  get 'door/index'

  root 'common#index'

end

app/models/audit_user.rb
class AuditUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/common_controller.rb
class CommonController < ApplicationController
  def index
  end
end

app/controllers/door_controller.rb
class DoorController < ApplicationController
  before_filter :authenticate_audit_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/common_helper.rb
module CommonHelper
end

app/helpers/door_helper.rb
module DoorHelper
end

app/views/common/index.html.slim
h1 Common#index
p Find me in app/views/common/index.html.slim

app/views/door/index.html.slim
- if audit_user_signed_in?
  p
    = current_audit_user.email 
h1 算法后台
p 准备中

app/views/layouts/_footer.html.slim
footer
  .container
    .row
      .col-md-4
        | &copy;2014
      .col-md-4
        ul.nav.nav-pills
          li
            a href='#' 
              | About Us
          li
            a href='#' 
              | Privacy Policy
      .col-md-4
        h4.text-right
          | 算法改变世界

app/views/layouts/_header.html.slim
.navbar.navbar-wrapper.navbar-fixed-top.navbar-default role='navigation' 
  .container
    .navbar-header
      a.navbar-brand href="#" 
        | 商品基因
    .collapse.navbar-collapse.navbar-ex1-collapse
      .collapse.navbar-collapse
        ul.nav.navbar-nav
          li.active
            =link_to "商品分类", "#"
          li
            =link_to "词典更新", "#"
          li
            =link_to "common", "/common/index"
          li.dropdown
            a.dropdown-toggle href="#"role="button"data-toggle="dropdown" 
              | 目录
              b.caret
            ul.dropdown-menu role="menu" 
              li
                =link_to "统计", "/commerce/commodity_statistic/statistic"
              li.divider
              li.dropdown-submenu
                a href='#'
                  | 更多
                ul.dropdown-menu
                  li
                    =link_to "内容", "#"

        / ul.nav.navbar-nav.navbar-right
        p.navbar-text.pull-right
          - if audit_user_signed_in?
            |  欢迎 &nbsp;&nbsp
            strong
              = current_audit_user.email
            | . 
            = link_to '修改资料', edit_audit_user_registration_path, :class => 'navbar-link'
            |  | 
            = link_to "退出", destroy_audit_user_session_path, method: :delete, :class => 'navbar-link'
          - else
            = link_to "注册", new_audit_user_registration_path, :class => 'navbar-link'
            |  | 
            = link_to "登陆", new_audit_user_session_path, :class => 'navbar-link'

        / ul.nav.navbar-nav.navbar-right
        /   li.active
        /     a href='#' 
        /       | 咨询
        /   li
        /     =link_to "帮助", "#"
        /   ul.dropdown-menu
        /     li
        /       a href='#' Cancel
        /     li
        /       a href='#' Confirm
        / form.navbar-form.navbar-right role='search' 
        /   .form-group
        /     input.form-control type='text'placeholder='Search' 
        /   button.btn.btn-default
        /     | Submit

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Moony
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/header'
    .container
      - if notice
        p.alert.alert-success
          = notice
      - if alert
        p.alert.alert-danger
          = alert
      = yield
    = render 'layouts/footer'

app/views/layouts/x.html.erb
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

app/views/layouts/x.html.slim
p.navbar-text.pull-right
  - if user_signed_in?
    |  Logged in as 
    strong
      = current_user.email
    | . 
    = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
    |  | 
    = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
  - else
    = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
    |  | 
    = link_to "Login", new_user_session_path, :class => 'navbar-link'